name: Backup Repository to Google Drive

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  backup-to-drive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone for Google Drive
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        run: |
          mkdir -p "$HOME/.config/rclone"
          printf "%s" "$SERVICE_ACCOUNT_JSON" > "$HOME/.config/rclone/service-account.json"
          {
            echo '[gdrive]'
            echo 'type = drive'
            echo 'scope = drive.file'
            echo 'service_account_file = $HOME/.config/rclone/service-account.json'
            echo 'root_folder_id = 1CdZMM4PGZuAB7tFeg3RlC6vxMXBh2rrD'
          } > "$HOME/.config/rclone/rclone.conf"

      - name: Sync repository to Google Drive
        run: |
          rclone sync . gdrive: \
            --config "$HOME/.config/rclone/rclone.conf" \
            --exclude ".git/**" \
            --fast-list
